name: Deploy Blazor WASM to GitHub Pages

on:
    push:
        branches: [main]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 8.0.101
                  include-prerelease: true

            - name: Publish .NET Core Project
              run: dotnet publish IMC/IMC.csproj -c Release -o release --nologo

            - name: Change base-tag in index.html to match GitHub Pages repository subdirectory
              run: sed -i 's/<base href="\/" \/>/<base href="\/balta-carnacode-desafio-03\/" \/>/g' release/wwwroot/index.html

            - name: Add .nojekyll file
              run: touch release/wwwroot/.nojekyll

            - name: Commit wwwroot to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: release/wwwroot
                  
# Copiado de https://gist.github.com/Carl-Hugo/721b848942083dc7739141a917a30653
